# docker-Specify the compose version
version: "3"

services:
  app:
    #Build a Dockerfile in the same directory
    build: .
    
    #Mount the files in the directory to the app directory in the container
    volumes: 
      - "./local/omeka-s/files:/var/www/html/files:rw"
    # Mount port 1000 on the container side to port 8080 on the host side.
    ports:
      - "8080:80"
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    #volumes:
    #  - "./local/mysql/data/omekas:/var/lib/mysql/data/omekas:rw"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: omekas
      MYSQL_USER: omekas
      MYSQL_PASSWORD: password
    logging:
      driver: "none"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - "8081:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    logging:
      driver: "none"